<a href="https://colab.research.google.com/github/damylusi/Accidents-In-France/blob/main/Modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.tree  import  DecisionTreeClassifier 
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.metrics import r2_score as Rsquared

from sklearn.tree  import  DecisionTreeClassifier 
from sklearn.ensemble  import  RandomForestClassifier  
from sklearn.linear_model  import  LogisticRegression
import xgboost as xgb
import lightgbm

import warnings 
warnings . filterwarnings ( 'ignore' )

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/model_dataset.csv')
data.head()

,Unnamed: 0,hour,lighting,intersection,atmosphere,collision,localisation,user_category,accident_severity,user_sex,pedestrian_action,road_category,traff_regime,longitud_profile,drawing_plan,surface_cond,acc_situation
0,0,14,Full day,Out of intersection,Cloudy weather,By the side,In built-up areas,Driver,Hospitalized wounded,Male,not specified,Departmental Road,Bidirectional,Dish,Curved right,normal,On the road
1,1,18,Full day,In intersection,Normal,Other,In built-up areas,Passenger,Hospitalized wounded,Female,not specified,Departmental Road,One way,Dish,Curved left,normal,On the road
2,2,19,Full day,Out of intersection,Normal,Other,Out of agglomeration,Pedestrian,Hospitalized wounded,Male,Opposite direction of the vehicle,Departmental Road,Bidirectional,Dish,Curved right,not normal,Off the road
3,3,19,Twilight or dawn,Out of intersection,Dazzling weather,By the side,In built-up areas,Driver,Hospitalized wounded,Male,not specified,Communal Way,Bidirectional,Dish,Straight part,normal,On the road
4,4,11,Full day,In intersection,Normal,By the side,In built-up areas,Passenger,Hospitalized wounded,Female,not specified,Communal Way,Bidirectional,Dish,Straight part,normal,On the road



```
# This is formatted as code
```

## Modelling

##Encoding

In [ ]:
le = LabelEncoder()

data.accident_severity = le.fit_transform(data.accident_severity)
data.user_sex = le.fit_transform(data.user_sex)
data.lighting = le.fit_transform(data.lighting)
data.intersection = le.fit_transform(data.intersection)
data.atmosphere = le.fit_transform(data.atmosphere)
data.collision = le.fit_transform(data.collision)
data.road_category = le.fit_transform(data.road_category)
data.traff_regime = le.fit_transform(data.traff_regime)
data.pedestrian_action = le.fit_transform(data.pedestrian_action)
data.localisation = le.fit_transform(data.localisation)
data.user_category = le.fit_transform(data.user_category)
data.longitud_profile = le.fit_transform(data.longitud_profile)
data.drawing_plan = le.fit_transform(data.drawing_plan)
data.surface_cond = le.fit_transform(data.surface_cond)
data.acc_situation = le.fit_transform(data.acc_situation)

In [ ]:
data.head(20)

,Unnamed: 0,hour,lighting,intersection,atmosphere,collision,localisation,user_category,accident_severity,user_sex,pedestrian_action,road_category,traff_regime,longitud_profile,drawing_plan,surface_cond,acc_situation
0,0,14,0,1,0,0,0,0,0,1,7,1,0,0,1,0,1
1,1,18,0,0,5,4,0,1,0,0,7,1,1,0,0,0,1
2,2,19,0,1,5,4,1,2,0,1,3,1,0,0,1,1,0
3,3,19,4,1,1,0,0,0,0,1,7,0,0,0,3,0,1
4,4,11,0,0,5,0,0,1,0,0,7,0,0,0,3,0,1
5,5,11,0,1,1,4,0,2,0,0,0,1,0,0,3,0,1
6,6,11,0,1,1,5,0,1,2,1,7,1,0,0,3,0,1
7,7,19,4,1,5,2,1,0,0,1,7,1,0,0,3,0,1
8,8,19,0,1,5,0,0,0,0,1,7,0,0,0,3,0,1
9,9,10,0,1,6,4,1,2,0,1,2,0,0,0,3,1,1
10,10,8,4,1,0,4,0,2,0,0,0,1,0,0,3,1,1
11,11,18,3,1,5,6,1,0,0,1,7,1,0,0,3,0,1
12,12,16,0,1,5,4,0,2,0,1,7,1,0,0,3,0,1
13,13,12,0,1,5,3,0,0,1,1,7,1,0,0,2,0,1
14,14,19,0,0,1,3,1,0,0,1,7,1,1,0,3,0,1
15,15,8,0,1,5,3,1,0,2,1,7,0,0,0,0,0,1
16,16,7,3,1,0,4,1,0,0,0,7,1,0,0,0,1,1
17,17,7,4,1,2,0,0,0,0,0,7,1,0,0,3,0,1
18,18,19,0,1,5,3,1,1,0,0,7,1,2,0,3,0,1
19,19,20,2,0,4,0,0,0,0,1,7,1,2,0,3,1,1

In [ ]:
df = data[['intersection',	'atmosphere',	'collision',	'localisation',	'user_category',	'accident_severity',	'user_sex',	'pedestrian_action',	'road_category',	'traff_regime',	'longitud_profile',	'drawing_plan',	'surface_cond',	'acc_situation']]
df = df.dropna()

In [ ]:
for  col  in  df . columns : 
    df [ col ]  =  df [ col ] . apply ( lambda  x :  int ( x )  )

df . head ()

,intersection,atmosphere,collision,localisation,user_category,accident_severity,user_sex,pedestrian_action,road_category,traff_regime,longitud_profile,drawing_plan,surface_cond,acc_situation
0,1,0,0,0,0,0,1,7,1,0,0,1,0,1
1,0,5,4,0,1,0,0,7,1,1,0,0,0,1
2,1,5,4,1,2,0,1,3,1,0,0,1,1,0
3,1,1,0,0,0,0,1,7,0,0,0,3,0,1
4,0,5,0,0,1,0,0,7,0,0,0,3,0,1

In [ ]:
x  =  df. drop (['accident_severity'],  axis = 1 ) 
y  =  df ['accident_severity']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

## Random Forest Classifier

In [ ]:
RFC = RandomForestClassifier(random_state = 0)
RFC.fit(x_train, y_train)
predict_RFC = RFC.predict(x_test)
accuracy_score(y_test, predict_RFC)

0.660147525917037

In [ ]:
report = classification_report(y_test, predict_RFC)
print(report)

              precision    recall  f1-score   support

           0       0.60      0.46      0.52     80390
           1       0.24      0.03      0.05     11696
           2       0.69      0.86      0.77    117911

    accuracy                           0.66    209997
   macro avg       0.51      0.45      0.45    209997
weighted avg       0.63      0.66      0.63    209997

## Logistic Regression

In [ ]:
LR = LogisticRegression(random_state = 0)
LR.fit(x_train, y_train)
predict_LR = LR.predict(x_test)
accuracy_score(y_test, predict_LR)

0.6514807354390777

In [ ]:
report = classification_report(y_test, predict_LR)
print(report)

              precision    recall  f1-score   support

           0       0.62      0.36      0.46     80390
           1       0.00      0.00      0.00     11696
           2       0.66      0.91      0.77    117911

    accuracy                           0.65    209997
   macro avg       0.43      0.43      0.41    209997
weighted avg       0.61      0.65      0.61    209997

## Decision Tree Classifier

In [ ]:
DT = DecisionTreeClassifier(min_samples_leaf = 10, max_leaf_nodes = 20)
DT.fit(x_train, y_train)
predict_DT = DT.predict(x_test)
accuracy_score(y_test, predict_DT)

0.6624237489106988

In [ ]:
report = classification_report(y_test, predict_DT)
print(report)

              precision    recall  f1-score   support

           0       0.61      0.44      0.51     80390
           1       0.00      0.00      0.00     11696
           2       0.68      0.88      0.77    117911

    accuracy                           0.66    209997
   macro avg       0.43      0.44      0.43    209997
weighted avg       0.62      0.66      0.63    209997

## XGBoost

In [ ]:
XGB = xgb.XGBRegressor()
XGB.fit(x_train, y_train)
predict_XGB = XGB.predict(x_test)
xgb_rsme = np.sqrt(Rsquared(y_test, predict_XGB))
print("R Squared for XGBoost: ", np.mean(xgb_rsme))

[15:03:51] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
R Squared for XGBoost:  0.4152445589933864

##LightGBM

In [ ]:
LGBM = lightgbm.LGBMRegressor()
LGBM.fit(x_train, y_train)
predict_LGBM = LGBM.predict(x_test)
lgbm_rsme = np.sqrt(Rsquared(y_test, predict_LGBM))
print("R Squared for LGBM: ", np.mean(lgbm_rsme))

R Squared for LGBM:  0.4205788906238923